import React, { useEffect, useState } from "react";
import socketConnection from "../utils/socket.io";
import Head from "next/head";
import Main from "../components/main/Main";
import LoginFormUI from "../components/login/LoginFormUI";

export default function Home(TeamID) {
  const [user, setUser] = useState("");
  const [socket, setSocket] = useState(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setUser(localStorage.getItem("user"));
    }
  }, []);

  useEffect(() => {
    window?.addEventListener("beforeunload", () => {
      socket?.close();
      socket?.disconnect();
    });
  }, [socket]);

  useEffect(() => {
    setSocket(socketConnection);
    return () => {
      socket?.close();
      socket?.disconnect();
      setSocket(null);
    };
  }, []);

  return (
    <>
      <Head>
        <title className="font-bold">Creavitech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fevicon.png" />
      </Head>
      {user ? <Main /> : <LoginFormUI />}
    </>
  );
}
