import React from "react";
import Head from "next/head";
import LoginFormUI from "../components/login/LoginFormUI";

const Login = () => {
  return (
    <>
      <Head>
        <title className="font-bold">Creavitech - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fevicon.png" />
      </Head>

      <main>
        <LoginFormUI />
      </main>
    </>
  );
};

export default Login;
