import React from "react";
import Head from "next/head";
import Signup2PageUI from "../components/signup2/Signup2PageUI";

const Signup2 = () => {
  return (
    <>
      <Head>
        <title className="font-bold">Creavitech - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fevicon.png" />
      </Head>

      <main>
        <Signup2PageUI />
      </main>
    </>
  );
};

export default Signup2;
