import React from "react";
import Head from "next/head";
import Signup3PageUI from "../components/signup3/Signup3PageUI";

const Signup3 = () => {
  return (
    <>
      <Head>
        <title className="font-bold">Creavitech - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fevicon.png" />
      </Head>

      <main>
        <Signup3PageUI />
      </main>
    </>
  );
};

export default Signup3;
