import React from "react";
import Head from "next/head";
import Signup4PageUI from "../components/signup4/Signup4PageUI";

const Signup4 = () => {
  return (
    <>
      <Head>
        <title className="font-bold">Creavitech - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fevicon.png" />
      </Head>

      <main>
        <Signup4PageUI />
      </main>
    </>
  );
};

export default Signup4;
